print('========================================Desafio009============================================')
tabuada = int(input('Digite qualquer numero para tabuada: '))
print('='*15)
print('{} x 0  = {:2} '.format(tabuada,tabuada * 0 ))
print('{} x 1  = {:2} '.format(tabuada,tabuada * 1))
print('{} x 2  = {:2} '.format(tabuada,tabuada * 2))
print('{} x 3  = {:2} '.format(tabuada,tabuada * 3))
print('{} x 4  = {:2} '.format(tabuada,tabuada * 4))
print('{} x 5  = {:2} '.format(tabuada,tabuada * 5))
print('{} x 6  = {:2} '.format(tabuada,tabuada * 6))
print('{} x 7  = {:2} '.format(tabuada,tabuada * 7))
print('{} x 8  = {:2} '.format(tabuada,tabuada * 8))
print('{} x 9  = {:2} '.format(tabuada,tabuada * 9))
print('{} x 10 = {:2} '.format(tabuada,tabuada * 10))
print('='*15)
